export {ChevronRightIcon} from './chevron-right';
export {ChevronLeftIcon} from './chevron-left';
export {DocumentAddIcon} from './document-add';
export {ArrowRightIcon} from './arrow-right';
export {ClipboardIcon} from './clipboard';
export {DocumentIcon} from './document';
export {SettingsIcon} from './settings';
export {LoadingIcon} from './loading';
export {LogoutIcon} from './logout';
export {PluginIcon} from './plugin';
export {CheckIcon} from './check';
export {CloseIcon} from './close';
export {InboxIcon} from './inbox';
export {MenuIcon} from './menu';
export {DashIcon} from './dash';
export {ChatIcon} from './chat';
export {LinkIcon} from './link';
export {UserIcon} from './user';
export {MailIcon} from './mail';
export {HomeIcon} from './home';
export {BookIcon} from './book';
export {MoonIcon} from './moon';
export {InfoIcon} from './info'
export {UndoIcon} from './undo'
export {LockIcon} from './lock'
export {SunIcon} from './sun';
