name: formizee

services:
  database:
    container_name: database
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/arm64
    restart: always
    ports:
      - "8080:8080"
      - "5001:5001"
    environment:
      SQLD_NODE: primary
      SQLD_DB_PATH: /var/lib/sqld/formizee.db
    volumes:
      - database:/var/lib/sqld

  storage:
    container_name: storage
    image: bitnami/minio:latest
    ports:
      - 3902:3902
      - 2903:2903
    environment:
      MINIO_ROOT_USER: minio_root_user
      MINIO_ROOT_PASSWORD: minio_root_password
      MINIO_API_PORT_NUMBER: 3902
      MINIO_CONSOLE_PORT_NUMBER: 3903
    volumes:
      - storage:/data

  api:
    container_name: api
    build:
      context: ..
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 8787:8787
    depends_on:
      - database
    environment:
      DATABASE_URL: "http://localhost:8080"

  vault:
    container_name: vault
    build:
      context: ..
      dockerfile: ./apps/vault/Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - database
      - storage
    environment:
      DATABASE_URL: "http://localhost:8080"

volumes:
  database:
  storage:
