name = "vault"
node_compat = true
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIROMENT = "development"
VERSION = "1.0.0"


[env.preview]
vars = { ENVIROMENT = "preview" }

[env.development]
vars = { ENVIROMENT = "development" }

[env.production]
name = "vault"
vars = { ENVIROMENT = "production", VERSION="1.0.0" }
