name = "vault"
node_compat = true
main = "src/index.ts"
compatibility_date = "2024-01-01"

account_id = "3050f3e2ff24fe0361c8aaa26369afd0"
workers_dev = true

[vars]
DOCS_URL = "https://docs.formizee.com"
ENVIROMENT = "development"
VERSION = "1.0.0"

[[r2_buckets]]
binding = "VAULT"
bucket_name = "vault"
preview_bucket_name = "preview"
