name = "vault"
node_compat = true
main = "src/index.ts"
compatibility_date = "2024-01-01"

account_id = "3050f3e2ff24fe0361c8aaa26369afd0"
workers_dev = true

[observability]
enabled = true
head_sampling_rate = 1

[vars]
DOCS_URL = "https://docs.formizee.com"
ENVIROMENT = "development"
VERSION = "1.0.0"

[env.production]
vars = { ENVIROMENT = "production", DOCS_URL="https://docs.formizee.com", VERSION="1.0.0" }
kv_namespaces = [ { binding = "VAULT", id = "03dacbed06b542a69a4abbfb52b72d2e" } ]
r2_buckets = [ { binding = "BUCKET", bucket_name = "vault" } ]
name = "vault"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "vault"
preview_bucket_name = "preview"

[[kv_namespaces]]
binding = "VAULT"
id = "03dacbed06b542a69a4abbfb52b72d2e"
preview_id = "c23ba34f403241089cdc39003e023788"
