name = "vault"
workers_dev = true
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability] 
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "cache"
id = "00000000000000000000000000000000"

[[kv_namespaces]]
binding = "keys"
id = "11111111111111111111111111111111"

[env.development]
vars = { ENVIROMENT = "development", DOCS_URL="https://docs.formizee.com", VERSION="1.0.0" }
