name = "vault"
workers_dev = true
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
account_id = "your account id"

[vars]
DOCS_URL="https://docs.formizee.com"
ENVIROMENT = "development"
VERSION="1.0.0"

[observability] 
head_sampling_rate = 1
enabled = true

[[kv_namespaces]]
binding = "cache"
id = "your kv id"
preview_id = "your kv preview id"

[[kv_namespaces]]
binding = "keys"
id = "your kv id"
preview_id = "your kv preview id"

[env.production]
vars = { ENVIROMENT = "production", DOCS_URL="https://docs.formizee.com", VERSION="1.0.0" }
