// Generated by Wrangler on Sun Jun 02 2024 18:18:29 GMT+0200 (hora de verano de Europa central)
// by running `wrangler types`

interface Env {
	SESSION_SECRET: string;
	SMTP_SECRET: string;
	LOGTAIL_SECRET: string;
	WORKER_ENV: string;
	DB: D1Database;
}
