// Generated by Wrangler on Thu May 23 2024 21:42:00 GMT+0200 (hora de verano de Europa central)
// by running `wrangler types`

interface Env {
	WORKER_ENV: "prod";
	SESSION_SECRET: string;
	SMTP_SECRET: string;
	DB: D1Database;
}
