// Generated by Wrangler on Wed May 22 2024 19:15:41 GMT+0200 (hora de verano de Europa central)
// by running `wrangler types`

interface Env {
	SESSION_SECRET: string;
	SMTP_SECRET: string;
	DB: D1Database;
}
