#:schema node_modules/wrangler/config-schema.json
name = "formizee-api"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

vars = { WORKER_ENV = "prod"}

[[d1_databases]]
binding = "DB"
database_name = "formizee"
database_id = "b781729f-67e8-4387-af61-ec6f5f78b71e"
