#:schema node_modules/wrangler/config-schema.json
name = "api"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "formizee-preview"
database_id = "6a07ef76-6305-4faf-80d0-83b13aaf0709"
