name = "api"
node_compat = true
main = "src/index.ts"
compatibility_date = "2024-01-01"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
API_URL = "http://localhost:8787"
DOCS_URL = "http://localhost:3002"
WEB_URL = "http://localhost:3000"
ENVIROMENT = "development"
VERSION = "1.0.0"

services = [ { binding = "VAULT", service = "vault" } ]

[env.preview]
vars = { ENVIROMENT = "preview" }

[env.development]
vars = { ENVIROMENT = "development" }

[env.production]
name = "api"
vars = { ENVIROMENT = "production", API_URL="https://api.formizee.com", DOCS_URL="https://docs.formizee.com", WEB_URL="https://formizee.com", VERSION="1.0.0" }
services = [ { binding = "VAULT", service = "vault" } ]
