name: Build
on:
  workflow_call:

jobs:
  commits:
    name: Conventional Commits
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Analyze Commits
        uses: webiny/action-conventional-commits@v1.3.0

  lint:
    name: Lint
    runs-on: blacksmith-4vcpu-ubuntu-2204
    env:
      TURBO_TEAM: ${{ secrets.VERCEL_ORG_ID }}
      TURBO_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.5
            
      - name: Setup Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Analyze Code
        run: pnpm lint

  build:
    name: Build
    runs-on: blacksmith-4vcpu-ubuntu-2204
    env:
      TURBO_TEAM: ${{ secrets.VERCEL_ORG_ID }}
      TURBO_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: pnpm turbo run build
