name: Continuous Deployment

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  checks:
    name: Check Repository Changes
    uses: ./.github/workflows/changed-packages.yml

  deploy_api:
    name: Deploy Formizee API
    runs-on: ubuntu-latest
    needs: [checks]
    if: needs.checks.outputs.api_changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.5

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "apps/api"
          packageManager: pnpm

  deploy_web:
    name: Deploy Formizee Webpage
    runs-on: ubuntu-latest
    needs: [checks]
    if: needs.checks.outputs.web_changed == 'true'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.5

      - name: Install Dependencies
        run: pnpm install | pnpm install --global vercel@latest

      - name: Build Artifacts
        run: pnpm turbo build

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_API_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_API_TOKEN }}

