name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy API
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.5

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "apps/api"
          packageManager: pnpm
        env:
          WORKER_ENV: "prod"
          SMTP_SECRET: ${{ secrets.SMTP_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
