name: Deploy
on:
  push:
    branches: [main]

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  vault_local_test:
    name: Test Vault
    uses: ./.github/workflows/job_test_vault_local.yaml

  vault_preview_deployment:
    needs:
      - vault_local_test
    uses: ./.github/workflows/job_deploy_vault_preview.yaml
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  vault_preview_test:
    needs:
      - vault_preview_deployment
    uses: ./.github/workflows/job_test_vault_preview.yaml
    with:
       VAULT_URL: https://vault-preview.formizee.com
    secrets:
      VAULT_SECRET_PREVIEW: ${{ secrets.VAULT_SECRET_PREVIEW }}
      DATABASE_URL_PREVIEW: ${{ secrets.SUBMISSIONS_DATABASE_URL_PREVIEW }}
      DATABASE_AUTH_TOKEN_PREVIEW: ${{ secrets.SUBMISSIONS_DATABASE_AUTH_TOKEN_PREVIEW }}

  vault_production_deployment:
    needs:
      - vault_preview_test
    uses: ./.github/workflows/job_deploy_vault_production.yaml
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}


  api_local_test:
    name: Test API
    uses: ./.github/workflows/job_test_api_local.yaml

  api_preview_deployment:
    needs:
      - api_local_test
    uses: ./.github/workflows/job_deploy_api_preview.yaml
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  api_preview_test:
    needs:
      - vault_preview_deployment
      - api_preview_deployment
    uses: ./.github/workflows/job_test_api_preview.yaml
    with:
       API_URL: https://api-preview.formizee.com
    secrets:
      VAULT_SECRET_PREVIEW: ${{ secrets.VAULT_SECRET_PREVIEW }}
      DATABASE_URL_PREVIEW: ${{ secrets.DATABASE_URL_PREVIEW }}
      DATABASE_AUTH_TOKEN_PREVIEW: ${{ secrets.DATABASE_AUTH_TOKEN_PREVIEW }}

  api_production_deployment:
    needs:
      - vault_production_deployment
      - api_preview_test
    uses: ./.github/workflows/job_deploy_api_production.yaml
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
