name: Deploy Vault Preview
on:
  workflow_call:
    secrets: 
      CLOUDFLARE_API_TOKEN: 
        required: true

jobs:
  deploy:
    environment: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: pnpm turbo run build --filter='./apps/vault'

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: apps/vault
          environment: preview
        env:
          VERSION: $(git rev-parse --short HEAD)
