name: Test API Preview
on:
  workflow_call:
    inputs:
      API_URL:
        type: string
        required: true
      VAULT_URL:
        type: string
        required: true
    secrets:
      VAULT_SECRET_PREVIEW:
        required: true
      DATABASE_URL_PREVIEW:
        required: true
      DATABASE_AUTH_TOKEN_PREVIEW:
        required: true

jobs:
  test:
    name: API Test Staging
    environment: Preview
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: pnpm turbo run build --filter=./apps/api

      - name: Test
        run: pnpm vitest run --bail=1
        working-directory: apps/api
        env:
          WEB_URL: https://formizee.com
          DOCS_URL: https://docs.formizee.com
          API_URL: ${{ inputs.API_URL }}
          VAULT_URL: ${{ inputs.VAULT_URL }}
          VAULT_SECRET: ${{ secrets.VAULT_SECRET_PREVIEW }}
          DATABASE_URL: ${{ secrets.DATABASE_URL_PREVIEW }}
          DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN_PREVIEW }}
