name: Test API Local
on:
  workflow_call:

jobs:
  test:
    name: API Test Local
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      TURBO_TEAM: ${{ secrets.VERCEL_ORG_ID }}
      TURBO_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Run containers
        run: docker compose -f ./deployment/docker-compose.yaml up -d


      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: pnpm turbo run build --filter=./apps/api...

      - name: Load Schema into main database
        run: "pnpm drizzle-kit push --config src/schemas/main/drizzle.config.ts"
        working-directory: internal/db
        env:
          DATABASE_URL: "http://localhost:8080"

      - name: Load Schema into vault database
        run: "pnpm drizzle-kit push --config src/schemas/submissions/drizzle.config.ts"
        working-directory: internal/db
        env:
          SUBMISSIONS_DATABASE_URL: "http://localhost:8081"

      - name: Test
        run: pnpm test
        working-directory: apps/api
        env:
          DATABASE_URL: "http://localhost:8080"
          VAULT_SECRET: ""

      - name: Dump logs
        if: always()
        run: docker compose -f ./deployment/docker-compose.yaml logs --no-color > ./docker.logs

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{github.run_id}}-${{github.run_number}}-api.logs
          path: docker.logs
          retention-days: 7
