name: Test Vault Local
on:
  workflow_call:

jobs:
  test:
    name: Vault Test Local
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      TURBO_TEAM: ${{ secrets.VERCEL_ORG_ID }}
      TURBO_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Run containers
        run: docker compose -f ./deployment/docker-compose.yaml up -d vault

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: pnpm turbo run build --filter=./apps/vault...

      - name: Load Schema into vault database
        run: "pnpm push:submissions"
        working-directory: internal/db
        env:
          DATABASE_URL: "http://localhost:8081"

      - name: Test
        run: pnpm test
        working-directory: apps/vault
        env:
          MASTER_KEY_V1: "eyJrZXlfb3BzIjpbImVuY3J5cHQiLCJkZWNyeXB0Il0sImV4dCI6dHJ1ZSwia3R5Ijoib2N0IiwiayI6ImdzTVRJc3ZGVzI0WEJqV0dSZk50ZjZFbUxGTXlHNWNlRnlsb2E3MEwyanMiLCJhbGciOiJBMjU2R0NNIn0"
          DATABASE_URL: "localhost:8081"
          ENVIROMENT: "development"
          EMIT_LOGS: "false"
          LOGTAIL_TOKEN: ""
          VAULT_SECRET: ""

      - name: Dump logs
        if: always()
        run: docker compose -f ./deployment/docker-compose.yaml logs --no-color > ./docker.logs

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{github.run_id}}-${{github.run_number}}-api.logs
          path: docker.logs
          retention-days: 7
