name: Pull Request

on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  workflow_dispatch:

jobs:
  test_packages:
    name: Test Packages
    uses: ./.github/workflows/job_test_unit.yaml

  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  test_vault:
    name: Test Vault
    uses: ./.github/workflows/job_test_vault_local.yaml

  test_api:
    name: Test API
    uses: ./.github/workflows/job_test_api_local.yaml
